FROM bitnami/elasticsearch:8.15.1

# ENV
# ELASTICSEARCH_PASSWORD = ...
# ELASTICSEARCH_ENABLE_SECURITY = true //need to enable password auth
# ELASTICSEARCH_SKIP_TRANSPORT_TLS = true //need to skip transport layer TLS, if not have write access, then can not save cert
# ELASTICSEARCH_ENABLE_REST_TLS = false //disable tls, will not required cert
# ELASTICSEARCH_HEAP_SIZE = 9000m //set heap size, more heap size will search more faster
# ELASTICSEARCH_MAX_ALLOWED_MEMORY_PERCENTAGE = 95 //set max allowed memory percentage
