services:
    swag:
        build:
            context: ./containers/swag
            dockerfile: Dockerfile
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=${PUID:-1001}
            - PGID=${PGID:-1002}
            - TZ=Etc/UTC
            - URL=giaang.id.vn
            - SUBDOMAINS=server, vphim-api
            - VALIDATION=http
            # - CERTPROVIDER=zerossl #optional
            - DNSPLUGIN=cloudflare #optional
            # - DUCKDNSTOKEN=<token> #optional
            - EMAIL=giang@giaang.id.vn #optional
            - ONLY_SUBDOMAINS=true #optional
            # - EXTRA_DOMAINS=<extradomains> #optional
            - STAGING=false #optional
        volumes:
            # - ./containers/swag/www:/config/www
            - ./containers/swag/nginx/proxy-confs:/config/nginx/proxy-confs
            - ./containers/swag/nginx/nginx.conf:/config/nginx/nginx.conf
            - ./.ssl/letsencrypt:/config/etc/letsencrypt # mount ssl key from container to work dir
        ports:
            - 80:80
            - 443:443
        networks:
            - vphim_net
        restart: unless-stopped

networks:
    vphim_net:
