@startuml Region - Get Single Region

actor User <<Actor>>
participant "RegionComponent (Next.js Admin)" as RegionComponent <<Component>>
participant "RegionResolver" as Resolver <<Resolver>>
participant "RegionsService" as RegionsService <<Service>>
participant "RegionRepository" as RegionRepository <<Repository>>
database "MongoDB" as MongoDB <<Database>>

User -> RegionComponent: Initiates get single region
RegionComponent -> Resolver: query region(input)
activate Resolver
Resolver -> RegionsService: getRegion(input)
activate Service

alt input contains _id
    Service -> Repo: findOneOrThrow(filterQuery: {_id})
    activate Repo
    Repo -> DB: findOne(query)
    activate DB
    DB --> Repo: return region or null
    deactivate DB
    
    alt region found
        Repo --> Service: return region
    else not found
        Repo --> Service: throw NotFoundException
    end
    deactivate Repo
    
else input contains slug
    Service -> Repo: findOneOrThrow(filterQuery: {slug})
    activate Repo
    Repo -> DB: findOne(query)
    activate DB
    DB --> Repo: return region or null
    deactivate DB
    
    alt region found
        Repo --> Service: return region
    else not found
        Repo --> Service: throw NotFoundException
    end
    deactivate Repo
    
else no valid input
    Service --> Resolver: throw HttpException(UNPROCESSABLE_ENTITY)
end

RegionsService --> Resolver: return region
deactivate Service
Resolver --> RegionComponent: return region
deactivate Resolver

@enduml 