import { type DefaultLayoutTranslations } from '@vidstack/react/player/layouts/default';

export const vietnameseLayoutTranslations: DefaultLayoutTranslations = {
    Unmute: 'Bật tiếng',
    'Caption Styles': 'Kiểu phụ đề',
    'Captions look like this': 'Phụ đề trông sẽ như thế này!',
    'Closed-Captions Off': 'Tắt phụ đề',
    'Closed-Captions On': 'Bật phụ đề',
    'Display Background': 'Hiển thị nền',
    'Enter Fullscreen': 'Vào chế độ toàn màn hình',
    'Enter PiP': 'Vào chế độ hình trong hình',
    'Exit Fullscreen': 'Thoát chế độ toàn màn hình',
    'Exit PiP': 'Thoát chế độ hình trong hình',
    'Google Cast': 'Google Cast',
    'Keyboard Animations': 'Hoạt ảnh bàn phím',
    'Seek Backward': 'Tua lùi',
    'Seek Forward': 'Tua tới',
    'Skip To Live': 'Chuyển đến trực tiếp',
    'Text Background': 'Nền văn bản',
    Accessibility: 'Khả năng tiếp cận',
    AirPlay: 'AirPlay',
    Announcements: 'Thông báo',
    Audio: 'Âm thanh',
    Auto: 'Tự động',
    Boost: 'Tăng cường',
    Captions: 'Phụ đề',
    Chapters: 'Chương',
    Color: 'Màu sắc',
    Connected: 'Đã kết nối',
    Connecting: 'Đang kết nối',
    Continue: 'Tiếp tục',
    Default: 'Mặc định',
    Disabled: 'Đã tắt',
    Disconnected: 'Đã ngắt kết nối',
    Download: 'Tải xuống',
    Family: 'Kiểu phông',
    Font: 'Phông chữ',
    Fullscreen: 'Toàn màn hình',
    LIVE: 'Trực tiếp',
    Loop: 'Lặp lại',
    Mute: 'Tắt tiếng',
    Normal: 'Bình thường',
    Off: 'Tắt',
    Opacity: 'Độ mờ',
    Pause: 'Tạm dừng',
    Play: 'Phát',
    PiP: 'Hình trong hình',
    Playback: 'Phát lại',
    Quality: 'Chất lượng',
    Replay: 'Phát lại',
    Reset: 'Đặt lại',
    Seek: 'Tìm kiếm',
    Settings: 'Cài đặt',
    Shadow: 'Bóng đổ',
    Size: 'Kích thước',
    Speed: 'Tốc độ',
    Text: 'Văn bản',
    Track: 'Bản nhạc',
    Volume: 'Âm lượng',
};
