module.exports = {
    apps: [
        {
            namespace: 'proxy',
            name: 'cloudflared',
            script: 'cloudflared',
            args: 'tunnel --no-autoupdate --metrics localhost:9000 run',
            env: {
                TUNNEL_TOKEN: process.env.CLOUDFLARED_TOKEN || 'giang',
            },
            output: '/dev/stdout',
            error: '/dev/stderr',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
            autorestart: true,
        },
        {
            namespace: 'cache',
            name: 'redis',
            script: '/usr/bin/redis-server',
            args: [
                '--port',
                process.env.REDIS_PORT || '6379',
                '--requirepass',
                process.env.REDIS_PASSWORD || 'giang',
                '--save',
                '""',
                '--appendonly',
                'no',
                '--maxmemory',
                '2048mb',
                '--maxmemory-policy',
                'allkeys-lru',
            ].join(' '),
            output: '/dev/stdout',
            error: '/dev/stderr',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
            autorestart: true,
            kill_timeout: 3000,
            shutdown_with_message: true,
            wait_ready: true,
            listen_timeout: 5000,
        },
        {
            namespace: 'apps',
            name: 'vphim-api',
            script: '/usr/src/app/dist/apps/api/main.js',
            instances: 4,
            exec_mode: 'cluster',
            max_memory_restart: '2G',
            output: '/dev/stdout',
            error: '/dev/stderr',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
            autorestart: true,
        },
    ],
};
