name: Build and push Docker image

on:
    # workflow_run:
    #     workflows: NX-CI
    #     types: completed
    #     branches: [main]
    push:
        branches: ['main']

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    DOCKER_DEFAULT_PLATFORM: linux/amd64

jobs:
    check-skip:
        # if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-22.04
        outputs:
            commit_message: ${{ steps.get_commit_message.outputs.commit_message }}
            skip_docker: ${{ steps.check_skip_docker.outputs.skip_docker }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get commit message
              id: get_commit_message
              run: |
                  commit_message=$(git log -1 --pretty=%B)
                  commit_message="${commit_message//'%'/'%25'}"
                  commit_message="${commit_message//$'\n'/' '}"
                  commit_message="${commit_message//$'\r'/' '}"
                  echo "commit_message=$commit_message" >> $GITHUB_OUTPUT

            - name: Check if commit message contains [skip docker]
              id: check_skip_docker
              run: |
                  if [[ "${{ steps.get_commit_message.outputs.commit_message }}" =~ "[skip docker]" ]]; then
                    echo "skip_docker=true" >> $GITHUB_OUTPUT
                    echo "Skip Docker build and push found in commit message."
                  else
                    echo "skip_docker=false" >> $GITHUB_OUTPUT
                  fi

    build:
        needs: [check-skip]
        if: ${{ needs.check-skip.outputs.skip_docker != 'true' }}
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKERHUB_USERNAME }}
                  password: ${{ env.DOCKERHUB_PASSWORD }}

            # - name: Free disk space up
            #   run: rm -rf /opt/hostedtoolcache

            - name: Install dotenvx
              run: curl -sfS https://dotenvx.sh/install.sh | sh

            - name: Set short SHA
              id: set_short_sha
              run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT

            - name: Create .env files
              run: |
                  for dir in "." "apps/fe" "apps/mnt" "apps/api" "containers/be-with-redis" "containers/be-redis-pm2" "containers/be-redis-es"; do
                    echo "# .env created" > "$dir/.env"
                  done

            - name: Prepare env for fe and mnt
              run: |
                  for dir in "apps/fe" "apps/mnt"; do
                    echo "NEXT_PUBLIC_API_URL='https://api.vephim.online'" >> "$dir/.env"
                    echo "NEXT_PUBLIC_IMAGES_URL='https://img.vephim.online'" >> "$dir/.env"
                    echo "NEXT_SHARP_PATH='/usr/src/app/node_modules/sharp'" >> "$dir/.env"
                  done
                  echo "NEXT_PUBLIC_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> ./apps/fe/.env
                  echo "NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}" >> ./apps/fe/.env

            - name: Build and push Docker images
              id: docker_build_push
              run: |
                function build_and_push() {
                  local compose_file="$1"
                  $DOCKER_DEFAULT_PLATFORM docker compose -f "$compose_file" build
                  $DOCKER_DEFAULT_PLATFORM docker compose -f "$compose_file" push
                }

                # Build and push with short SHA tag
                dotenvx set --plain COMPOSE_TAG ${{ steps.set_short_sha.outputs.SHORT_SHA }}
                build_and_push "docker-compose.yml"
                build_and_push "docker-compose.bundle.yml"

                # Build and push with latest tag if specified
                if [[ "${{ needs.check-skip.outputs.commit_message }}" =~ "[docker-latest]" ]]; then
                  dotenvx set --plain COMPOSE_TAG latest
                  build_and_push "docker-compose.yml"
                  build_and_push "docker-compose.bundle.yml"
                fi

            - name: Remove .env file
              run: rm .env
