name: Android App APK Build

on:
    push:
        branches:
            - feat/eas
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: 'npm'

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3

            - name: Setup Expo
              uses: expo/expo-github-action@v8
              with:
                  expo-version: latest
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build Android app
              run: yarn nx build mobile -- --platform android --non-interactive --no-wait --output ${{ github.workspace }}/vephim.apk
            - name: Upload APK artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-release
                  path: ${{ github.workspace }}/app-release.apk
