name: Android App APK Build

on:
    push:
        branches:
            - feat/eas

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Enable Corepack for Yarn v4
              run: corepack enable

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3

            - name: Setup Expo
              uses: expo/expo-github-action@v8
              with:
                  expo-version: latest
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Switch to Yarn Classic
              run: |
                  npm install -g yarn@1.22.19
                  yarn set version classic

            - name: Reinstall dependencies with Yarn Classic
              run: |
                  yarn install --force

            - name: Build Android app
              run: |
                  cd apps/mobile
                  yarn nx build mobile -- --platform android --profile preview --non-interactive --local --output ${{ github.workspace }}/vephim.apk

            - name: Upload APK artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-release
                  path: ${{ github.workspace }}/vephim.apk
